version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: mortech-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mortech_secure_password
      POSTGRES_DB: mortech_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
