export const seedProducts = [
  {
    name: 'Dahua Camera IP Bullet 4MP PoE Full-color Network',
    description: 'Camera IP Bullet Dahua 4MP PoE Full-color Network',
    brand: 'Dahua',
    category: 'Videosurveillance',
    subcategory: 'Camera IP Dahua',
    badge: '4MP PoE',
    price: 680,
    stock: 10,
    imageUrl: 'https://via.placeholder.com/420x280?text=Dahua+Camera+IP+Bullet'
  },
  {
    name: 'Dahua Camera IP Dome 2MP Wide View Night Vision',
    description: 'Camera IP Dahua 2MP Dome avec vision nocturne et detection intelligente',
    brand: 'Dahua',
    category: 'Videosurveillance',
    subcategory: 'Camera IP Dahua',
    badge: '2MP Dome',
    price: 520,
    stock: 8,
    imageUrl: 'https://via.placeholder.com/420x280?text=Dahua+Camera+IP+Dome'
  },
  {
    name: 'Dahua Camera Analogique 5MP Turret IR 40m',
    description: 'Camera analogique Dahua 5MP Turret avec infrarouge 40m',
    brand: 'Dahua',
    category: 'Videosurveillance',
    subcategory: 'Camera Analog Dahua',
    badge: 'IR 40m',
    price: 450,
    stock: 12,
    imageUrl: 'https://via.placeholder.com/420x280?text=Dahua+Camera+Analogique'
  },
  {
    name: 'Hikvision Turbo HD PTZ SD2A500HB-GN-AW-PV-S2',
    description: 'Camera PTZ Hikvision Turbo HD avec zoom optique et fonction Wi-Fi',
    brand: 'Hikvision',
    category: 'Videosurveillance',
    subcategory: 'Camera IP Hikvision',
    badge: 'PTZ Wi-Fi',
    price: 6000,
    stock: 4,
    imageUrl: 'https://via.placeholder.com/420x280?text=Hikvision+PTZ'
  },
  {
    name: 'Hikvision Camera IP Wi-Fi Ranger 2 IPC-A22EP-G',
    description: 'Camera IP Hikvision Wi-Fi Ranger 2 pour surveillance sans fil',
    brand: 'Hikvision',
    category: 'Videosurveillance',
    subcategory: 'Camera IP Hikvision',
    badge: 'Best seller',
    price: 384,
    stock: 18,
    imageUrl: 'https://via.placeholder.com/420x280?text=Hikvision+Camera+IP+Ranger'
  },
  {
    name: 'Camera IP Hikvision Bullet 4MP Lite Full-color',
    description: 'Camera IP Hikvision Bullet 4MP Lite avec couleur nocturne',
    brand: 'Hikvision',
    category: 'Videosurveillance',
    subcategory: 'Camera IP Hikvision',
    badge: '4MP',
    price: 624,
    stock: 25,
    imageUrl: 'https://via.placeholder.com/420x280?text=Hikvision+Bullet+4MP'
  },
  {
    name: 'Camera Analogique 5MP IR 40m Bullet DS-2CE10KF0T-LFS',
    description: 'Camera analogique Hikvision Bullet 5MP avec portee IR 40m',
    brand: 'Hikvision',
    category: 'Videosurveillance',
    subcategory: 'Camera Analog Hikvision',
    badge: 'IR 40m',
    price: 420,
    stock: 22,
    imageUrl: 'https://via.placeholder.com/420x280?text=Hikvision+Analog+Bullet'
  },
  {
    name: 'DVR 2MP 4 channel DS-7204HGHI-M1',
    description: 'DVR Hikvision 2MP 4 canaux pour enregistrement video',
    brand: 'Hikvision',
    category: 'Videosurveillance',
    subcategory: 'DVR Hikvision',
    badge: 'DVR',
    price: 546,
    stock: 0,
    imageUrl: 'https://via.placeholder.com/420x280?text=Hikvision+DVR'
  },
  {
    name: 'Point acces exterieur RG-RAP6202(G) Wi-Fi 5 AC1300',
    description: 'Point d acces exterieur Ruijie Reyee RG-RAP6202(G) Wi-Fi 5 AC1300',
    brand: 'Ruijie Reyee',
    category: 'Equipement Reseaux',
    subcategory: 'Switch PoE',
    badge: 'Outdoor',
    price: 1625,
    stock: 8,
    imageUrl: 'https://disismaroc.com/storage/products/16/381/disismaroc-point-dacces-exterieur-omnidirectionnel-rg-rap6202g-wi-fi-5-ac1300--1724167262-6802.png'
  },
  {
    name: 'Routeur Mesh Wi-Fi 6 3200M dual band Gigabit',
    description: 'Routeur Mesh Wi-Fi 6 dual band Gigabit',
    brand: 'Ruijie Reyee',
    category: 'Equipement Reseaux',
    subcategory: 'Switch',
    badge: 'Wi-Fi 6',
    price: 1513.2,
    stock: 12,
    imageUrl: 'https://disismaroc.com/storage/products/16/385/disismaroc-routeur-mesh-wi-fi-6-3200m-dual-band-gigabit-rg-ew3200gx-pro--1724168243-2597.png'
  },
  {
    name: 'Sonoff 4CH Pro R3 module domotique',
    description: 'Module domotique Sonoff 4CH Pro R3',
    brand: 'Sonoff',
    category: 'Domotique',
    subcategory: 'Sonoff',
    badge: 'Smart home',
    price: 395,
    stock: 15,
    imageUrl: 'https://via.placeholder.com/420x280?text=Sonoff+4CH+Pro'
  },
  {
    name: 'Dahua NVR 8 canaux PoE Resolution 4MP',
    description: 'NVR Dahua 8 canaux PoE resolution 4MP',
    brand: 'Dahua',
    category: 'Videosurveillance',
    subcategory: 'NVR Dahua',
    badge: 'NVR 8CH PoE',
    price: 1380,
    stock: 10,
    imageUrl: 'https://via.placeholder.com/420x280?text=Dahua+NVR+8+canaux'
  },
  {
    name: 'NVR Hikvision 8 canaux PoE pour camera IP',
    description: 'NVR Hikvision 8 canaux PoE pour camera IP',
    brand: 'Hikvision',
    category: 'Videosurveillance',
    subcategory: 'NVR Hikvision',
    badge: 'NVR PoE',
    price: 1250,
    stock: 9,
    imageUrl: 'https://via.placeholder.com/420x280?text=Hikvision+NVR+8CH'
  },
  {
    name: 'Dahua XVR 4MP 8 canaux DVR/NVR Hybride',
    description: 'XVR Dahua 4MP 8 canaux hybride DVR/NVR',
    brand: 'Dahua',
    category: 'Videosurveillance',
    subcategory: 'XVR Dahua',
    badge: 'Hybride 8CH',
    price: 890,
    stock: 14,
    imageUrl: 'https://via.placeholder.com/420x280?text=Dahua+XVR+4MP'
  },
  {
    name: 'Videophone IP ecran tactile 7 pouces avec interphone',
    description: 'Videophone IP tactile 7 pouces',
    brand: 'Hikvision',
    category: 'Videosurveillance',
    subcategory: 'Videophone Hikvision',
    badge: 'Videophone',
    price: 1850,
    stock: 6,
    imageUrl: 'https://via.placeholder.com/420x280?text=Hikvision+Videophone'
  },
  {
    name: 'Dahua Videophone IP 7 pouces Ecran Tactile',
    description: 'Videophone IP Dahua 7 pouces ecran tactile',
    brand: 'Dahua',
    category: 'Videosurveillance',
    subcategory: 'Videophone Dahua',
    badge: 'Videophone 7"',
    price: 2150,
    stock: 7,
    imageUrl: 'https://via.placeholder.com/420x280?text=Dahua+Videophone'
  },
  {
    name: 'Pointeuse ZKTeco biometrie empreinte et badge',
    description: 'Pointeuse ZKTeco biometrie empreinte et badge',
    brand: 'ZKTeco',
    category: 'Controle Dacces et Pointeuse',
    subcategory: 'Pointeuse ZKTeco',
    badge: 'Pointage',
    price: 1450,
    stock: 11,
    imageUrl: 'https://via.placeholder.com/420x280?text=ZKTeco+Pointeuse'
  },
  {
    name: 'Terminal controle d acces Hikvision badge RFID',
    description: 'Terminal de controle d acces Hikvision avec badge RFID',
    brand: 'Hikvision',
    category: 'Controle Dacces et Pointeuse',
    subcategory: "Controle d'acces hikvision",
    badge: 'RFID',
    price: 1180,
    stock: 8,
    imageUrl: 'https://via.placeholder.com/420x280?text=Hikvision+Controle+Acces'
  },
  {
    name: 'Kit controle d acces Dahua avec lecteur et alimentation',
    description: 'Kit controle d acces Dahua complet avec lecteur et alimentation',
    brand: 'Dahua',
    category: 'Controle Dacces et Pointeuse',
    subcategory: "Controle D'acces Dahua",
    badge: 'Kit acces',
    price: 980,
    stock: 13,
    imageUrl: 'https://www.dynamic-computers.rs/images/products/big/134163.jpg'
  },
  {
    name: 'Kit alarme Ajax Hub avec detecteur mouvement',
    description: 'Kit alarme Ajax Hub avec detecteur de mouvement sans fil',
    brand: 'Ajax',
    category: 'Securite',
    subcategory: 'Alarme Ajax',
    badge: 'Alarme',
    price: 2890,
    stock: 5,
    imageUrl: 'https://via.placeholder.com/420x280?text=Ajax+Alarm+Kit'
  },
  {
    name: 'Detecteur intrusion Hikvision sans fil PIR',
    description: 'Detecteur intrusion Hikvision sans fil PIR',
    brand: 'Hikvision',
    category: 'Securite',
    subcategory: 'ALARME HIKVISION',
    badge: 'Intrusion',
    price: 390,
    stock: 20,
    imageUrl: 'https://via.placeholder.com/420x280?text=Hikvision+PIR'
  },
  {
    name: 'Detecteur incendie conventionnel avec sirene',
    description: 'Detecteur incendie conventionnel avec sirene',
    brand: 'Nugelec',
    category: 'Securite',
    subcategory: 'Incendie Nugelec',
    badge: 'Incendie',
    price: 320,
    stock: 15,
    imageUrl: 'https://materiel-securite-incendie.fireless.fr/5740-large_default/detecteur-thermovelocimetrique-s3000-nug30247.jpg'
  },
  {
    name: 'Cable alarme 6 conducteurs pour systeme intrusion',
    description: 'Cable alarme 6 conducteurs pour systeme intrusion',
    brand: 'Alarm Cable',
    category: 'Securite',
    subcategory: 'Cable alarm',
    badge: 'Cable alarm',
    price: 180,
    stock: 30,
    imageUrl: 'https://via.placeholder.com/420x280?text=Cable+Alarme'
  },
  {
    name: 'Kit alarme Dahua sans fil avec sirene et detecteur',
    description: 'Kit alarme Dahua sans fil avec sirene et detecteur',
    brand: 'Dahua',
    category: 'Securite',
    subcategory: 'Alarme Dahua',
    badge: 'Dahua',
    price: 1690,
    stock: 10,
    imageUrl: 'https://via.placeholder.com/420x280?text=Dahua+Alarm+Kit'
  },
  {
    name: 'Alarme autonome avec sirene integree et detecteur',
    description: 'Alarme autonome avec sirene integree et detecteur',
    brand: 'Autonome',
    category: 'Securite',
    subcategory: 'Alarme Autonome',
    badge: 'Autonome',
    price: 590,
    stock: 18,
    imageUrl: 'https://via.placeholder.com/420x280?text=Alarme+Autonome'
  },
  {
    name: 'Cable incendie CR1 rouge 2 conducteurs',
    description: 'Cable incendie CR1 rouge 2 conducteurs',
    brand: 'Fire Cable',
    category: 'Securite',
    subcategory: 'Cable incendie',
    badge: 'Cable feu',
    price: 220,
    stock: 25,
    imageUrl: 'https://via.placeholder.com/420x280?text=Cable+Incendie'
  },
  {
    name: 'Detecteur incendie adressable optique pour boucle SSI',
    description: 'Detecteur incendie adressable optique pour boucle SSI',
    brand: 'Nugelec',
    category: 'Securite',
    subcategory: 'Incendie Adressable',
    badge: 'Adressable',
    price: 520,
    stock: 12,
    imageUrl: 'https://materiel-securite-incendie.fireless.fr/5740-large_default/detecteur-thermovelocimetrique-s3000-nug30247.jpg'
  },
  {
    name: 'Detecteur incendie conventionnel optique avec base',
    description: 'Detecteur incendie conventionnel optique avec base',
    brand: 'Nugelec',
    category: 'Securite',
    subcategory: 'Incendie conventionnelle',
    badge: 'Conventionnel',
    price: 290,
    stock: 20,
    imageUrl: 'https://materiel-securite-incendie.fireless.fr/5740-large_default/detecteur-thermovelocimetrique-s3000-nug30247.jpg'
  },
  {
    name: 'Kit alarme incendie avec declencheur manuel et sirene',
    description: 'Kit alarme incendie avec declencheur manuel et sirene',
    brand: 'Securite Incendie',
    category: 'Securite',
    subcategory: 'Alarme incendie',
    badge: 'Alarme feu',
    price: 1150,
    stock: 11,
    imageUrl: 'https://materiel-securite-incendie.fireless.fr/5740-large_default/detecteur-thermovelocimetrique-s3000-nug30247.jpg'
  },
  {
    name: 'Armoire informatique etanche murale 12U IP65',
    description: 'Armoire informatique etanche murale 12U IP65',
    brand: 'Linkbasic',
    category: 'Equipement Reseaux',
    subcategory: 'Armoire Informatique Etanche',
    badge: 'IP65',
    price: 2450,
    stock: 9,
    imageUrl: 'https://via.placeholder.com/420x280?text=Armoire+IP65'
  },
  {
    name: 'Armoire informatique reseau 19 pouces 9U',
    description: 'Armoire informatique reseau 19 pouces 9U',
    brand: 'Digitus',
    category: 'Equipement Reseaux',
    subcategory: 'Armoire Informatique',
    badge: '19 pouces',
    price: 1550,
    stock: 7,
    imageUrl: 'https://via.placeholder.com/420x280?text=Armoire+19U'
  },
  {
    name: 'Plateau fixe et multiprise pour armoire reseau',
    description: 'Plateau fixe et multiprise pour armoire reseau',
    brand: 'Mortech',
    category: 'Equipement Reseaux',
    subcategory: "Accessoires d'Armoire",
    badge: 'Accessoire',
    price: 320,
    stock: 20,
    imageUrl: 'https://via.placeholder.com/420x280?text=Plateau+Armoire'
  },
  {
    name: 'Switch TP-Link Gigabit 8 ports metal',
    description: 'Switch TP-Link Gigabit 8 ports metal',
    brand: 'TP-Link',
    category: 'Equipement Reseaux',
    subcategory: 'Switch TP-Link',
    badge: 'TP-Link',
    price: 290,
    stock: 31,
    imageUrl: 'https://via.placeholder.com/420x280?text=TP-Link+Switch+8+ports'
  },
  {
    name: 'Switch PoE 8 ports pour cameras IP',
    description: 'Switch PoE 8 ports pour cameras IP',
    brand: 'Ruijie Reyee',
    category: 'Equipement Reseaux',
    subcategory: 'Switch PoE',
    badge: 'PoE',
    price: 890,
    stock: 17,
    imageUrl: 'https://via.placeholder.com/420x280?text=Switch+PoE+8+ports'
  },
  {
    name: 'Switch reseau 8 ports Gigabit non manageable',
    description: 'Switch reseau 8 ports Gigabit non manageable',
    brand: 'D-Link',
    category: 'Equipement Reseaux',
    subcategory: 'Switch 8 port',
    badge: '8 ports',
    price: 260,
    stock: 28,
    imageUrl: 'https://via.placeholder.com/420x280?text=Switch+8+ports'
  },
  {
    name: 'Switch 16 ports Gigabit rackable',
    description: 'Switch 16 ports Gigabit rackable',
    brand: 'TP-Link',
    category: 'Equipement Reseaux',
    subcategory: 'Switch 16 port',
    badge: '16 ports',
    price: 760,
    stock: 14,
    imageUrl: 'https://via.placeholder.com/420x280?text=Switch+16+ports'
  },
  {
    name: 'Switch 24 ports Gigabit pour baie reseau',
    description: 'Switch 24 ports Gigabit pour baie reseau',
    brand: 'Cisco',
    category: 'Equipement Reseaux',
    subcategory: 'Switch 24 port',
    badge: '24 ports',
    price: 1450,
    stock: 10,
    imageUrl: 'https://via.placeholder.com/420x280?text=Switch+24+ports'
  },
  {
    name: 'Box domotique Somfy TaHoma Switch',
    description: 'Box domotique Somfy TaHoma Switch',
    brand: 'Somfy',
    category: 'Domotique',
    subcategory: 'TAHOMA SOMFY',
    badge: 'TaHoma',
    price: 1890,
    stock: 6,
    imageUrl: 'https://via.placeholder.com/420x280?text=Somfy+TaHoma'
  },
  {
    name: 'Moniteur interieur Akuvox pour maison connectee',
    description: 'Moniteur interieur Akuvox pour maison connectee',
    brand: 'Akuvox',
    category: 'Domotique',
    subcategory: 'AKUVOX',
    badge: 'Akuvox',
    price: 2450,
    stock: 5,
    imageUrl: 'https://via.placeholder.com/420x280?text=Akuvox+Moniteur'
  },
  {
    name: 'Interrupteur intelligent Tuya Wi-Fi tactile',
    description: 'Interrupteur intelligent Tuya Wi-Fi tactile',
    brand: 'Tuya',
    category: 'Domotique',
    subcategory: 'Tuya',
    badge: 'Tuya',
    price: 180,
    stock: 22,
    imageUrl: 'https://via.placeholder.com/420x280?text=Tuya+Switch'
  },
  {
    name: 'Module relais Shelly Plus 1 Wi-Fi',
    description: 'Module relais Shelly Plus 1 Wi-Fi',
    brand: 'Shelly',
    category: 'Domotique',
    subcategory: 'Shelly',
    badge: 'Shelly',
    price: 210,
    stock: 24,
    imageUrl: 'https://via.placeholder.com/420x280?text=Shelly+Plus+1'
  },
  {
    name: 'Serrure intelligente connectee avec clavier et badge',
    description: 'Serrure intelligente connectee avec clavier et badge',
    brand: 'Mortech',
    category: 'Controle Dacces et Pointeuse',
    subcategory: 'Serrure intelligente',
    badge: 'Smart lock',
    price: 1450,
    stock: 9,
    imageUrl: 'https://via.placeholder.com/420x280?text=Serrure+intelligente'
  },
  {
    name: 'Controle d acces ZKTeco autonome empreinte et RFID',
    description: 'Controle d acces ZKTeco autonome empreinte et RFID',
    brand: 'ZKTeco',
    category: 'Controle Dacces et Pointeuse',
    subcategory: "Controle D'acces ZKTeco",
    badge: 'ZKTeco',
    price: 1280,
    stock: 8,
    imageUrl: 'https://zkteco.technology/wp-content/uploads/2022/01/c00444fc2e4cb4d4f513af79ca6e1fe3.png'
  },
  {
    name: 'Pointeuse Hikvision biometrie visage et badge',
    description: 'Pointeuse Hikvision biometrie visage et badge',
    brand: 'Hikvision',
    category: 'Controle Dacces et Pointeuse',
    subcategory: 'Pointeuse hikvision',
    badge: 'Pointage',
    price: 1750,
    stock: 7,
    imageUrl: 'https://via.placeholder.com/420x280?text=Hikvision+Pointeuse'
  },
  {
    name: 'Pack detection intrusion avec centrale, detecteur et sirene',
    description: 'Pack detection intrusion Hikvision sans fil',
    brand: 'Hikvision',
    category: 'Securite',
    subcategory: 'Detection intrusion',
    badge: 'Intrusion',
    price: 2190,
    stock: 6,
    imageUrl: 'https://www.ctccommunications.com.au/cdn/shop/products/Hikvison-Wireless-PIR-Detector-DS-PDP15P-EG2-WB_1_ba917418-9201-478e-973f-3447445c2683_600x600.jpg?v=1752449306'
  },
  {
    name: 'Pack detection incendie avec detecteur, declencheur et sirene',
    description: 'Pack detection incendie complet Nugelec',
    brand: 'Nugelec',
    category: 'Securite',
    subcategory: 'Detection incendie',
    badge: 'Incendie',
    price: 1380,
    stock: 10,
    imageUrl: 'https://materiel-securite-incendie.fireless.fr/5740-large_default/detecteur-thermovelocimetrique-s3000-nug30247.jpg'
  },
  {
    name: 'RAM Kingston 16GB DDR4 3200MHz UDIMM',
    description: 'RAM Kingston 16GB DDR4 3200MHz UDIMM',
    brand: 'Kingston',
    category: 'Materiel Informatique',
    subcategory: 'RAM',
    badge: 'DDR4 16GB',
    price: 450,
    stock: 30,
    imageUrl: 'https://via.placeholder.com/420x280?text=Kingston+16GB+DDR4'
  },
  {
    name: 'SanDisk SSD Plus 1TB SATA III',
    description: 'SanDisk SSD Plus 1TB SATA III',
    brand: 'SanDisk',
    category: 'Materiel Informatique',
    subcategory: 'SSDs',
    badge: 'SSD 1TB',
    price: 1200,
    stock: 28,
    imageUrl: 'https://via.placeholder.com/420x280?text=SanDisk+SSD+1TB'
  },
  {
    name: 'WD My Passport Disque dur externe portable 2TB',
    description: 'Disque dur externe portable WD My Passport 2TB',
    brand: 'WD',
    category: 'Materiel Informatique',
    subcategory: 'Stockage portable',
    badge: 'Portable 2TB',
    price: 1050,
    stock: 22,
    imageUrl: 'https://via.placeholder.com/420x280?text=WD+My+Passport+2TB'
  },
  {
    name: 'WD Blue Disque dur interne 1TB 3.5 pouces',
    description: 'Disque dur interne WD Blue 1TB 3.5 pouces',
    brand: 'WD',
    category: 'Materiel Informatique',
    subcategory: 'HDD',
    badge: 'HDD 1TB',
    price: 680,
    stock: 32,
    imageUrl: 'https://via.placeholder.com/420x280?text=WD+Blue+1TB'
  }
];
