import {
  Camera,
  ShieldCheck,
  Home,
  CircleUserRound,
  Network,
} from 'lucide-react';

import logo from './assets/mortech-logo-cropped.png';
import ramMemoryImage from './assets/products/Memoire RAM DDR4 8GB 3200MHz.jpg';
import sandiskSsdImage from './assets/products/SSD SATA 480GB pour ordinateur portable.webp';
import portableDriveImage from './assets/products/Disque dur portable externe 2TB USB 3.0.webp';
import wdHddImage from './assets/products/Disque dur HDD 1TB SATA 3.5 pouces.webp';
import hikvisionTurboPtzImage from './assets/products/Hikvision Turbo HD PTZ SD2A500HB-GN-AW-PV-S2.webp';
import hikvisionWifiRangerImage from './assets/products/Hikvision Camera IP Wi-Fi Ranger.jpg';
import hikvisionBulletImage from './assets/products/Camera IP Hikvision Bullet 4MP Lite Full-color.webp';
import cameraAnalogImage from './assets/products/Camera Analogique 5MP IR 40m Bullet DS-2CE10KF0T-LFS.webp';
import dvrImage from './assets/products/DVR 2MP 4 channel DS-7204HGHI-M1.webp';
import nvrImage from './assets/products/NVR Hikvision 8 canaux PoE pour camera IP.webp';
import videophoneImage from './assets/products/DS-KIS212-4-Wire-HD-Video-Intercom-Kit-Hikvision-1-min.webp';
import dahuaBulletImage from './assets/products/Dahua Camera IP Bullet 4MP PoE Full-color Network.webp';
import dahuaDomeImage from './assets/products/Dahua Camera IP Dome 2MP Wide View Night Vision.webp';
import dahuaNvrImage from './assets/products/Dahua NVR 8 canaux PoE Resolution 4MP.png';
import dahuaXvrImage from './assets/products/Dahua XVR 4MP 8 canaux DVR-NVR Hybride.webp';
import dahuaVideophoneImage from './assets/products/Dahua Videophone IP 7 pouces Ecran Tactile.webp';
import dahuacameraAnalogImage from './assets/products/Dahua Camera Analogique 5MP Turret IR 40m.jpg';
import Armoireinformatiqueetanche from './assets/products/Armoire informatique etanche murale 12U IP65.webp';
import Armoireinformatique from './assets/products/Armoire informatique reseau 19 pouces 9U.jpg';
import Plateaufixe from './assets/products/Plateau fixe et multiprise pour armoire reseau.webp';
import switchTpLinkImage from './assets/products/Switch TP-Link Gigabit 8 ports metal.jpeg';
import switchPoeImage from './assets/products/Switch PoE 8 ports pour cameras IP.webp';
import switch8PortImage from './assets/products/Switch reseau 8 ports Gigabit non manageable.png';
import switch16PortImage from './assets/products/Switch 16 ports Gigabit rackable.webp';
import switch24PortImage from './assets/products/Switch 24 port.jpeg';
import somfyTahomaImage from './assets/products/Box domotique Somfy TaHoma Switch.jpg';
import tuyaSwitchImage from './assets/products/Interrupteur intelligent Tuya Wi-Fi tactile.webp';
import shellyRelayImage from './assets/products/Module relais Shelly Plus 1 Wi-Fi.png';
import akuvoxMonitorImage from './assets/products/Moniteur interieur Akuvox pour maison connectee.jpg';
import sonoffModuleImage from './assets/products/Sonoff 4CH Pro R3 module domotique.webp';
import hikvisionAccessControlImage from './assets/products/hikvision-access-control-ds-k1t804amf-terminal-de-controle-d-acces-presence-avec-ecran-et-clavier.jpg';
import smartLockImage from './assets/products/Serrure intelligente connectee avec clavier et badge.webp';
import pointeuseHikvisionImage from './assets/products/Pointeuse Hikvision biometrie visage et badge.webp';
import pointeuseZktecoImage from './assets/products/Pointeuse ZKTeco biometrie empreinte et badge.jpeg';
import kitAlarmeAjaxImage from './assets/products/Kit alarme Ajax Hub avec detecteur mouvemen.webp';
import detecteurIntrusionHikvisionImage from './assets/products/Detecteur intrusion Hikvision sans fil PIR.webp';
import cableAlarmeImage from './assets/products/Cable alarme 6 conducteurs pour systeme intrusion.jpeg';
import alarmeAutonomeImage from './assets/products/Alarme autonome avec sirene integree et detecteur.webp';
import kitAlarmeDahuaImage from './assets/products/Kit alarme Dahua sans fil avec sirene et detecteur.webp';
import cableIncendieImage from './assets/products/Cable incendie CR1 rouge 2 conducteurs.jpeg';

export const categoryGroups = [
  {
    name: 'Materiel Informatique',
    sections: [
      { name: 'Stockage', links: ['HDD', 'Cartes memoire', 'Stockage portable', 'SSDs', 'RAM'] },
    ],
  },
  {
    name: 'Videosurveillance',
    sections: [
      { name: 'Hikvision', links: ['Camera Analog Hikvision', 'Camera IP Hikvision', 'DVR Hikvision', 'NVR Hikvision', 'Videophone Hikvision'] },
      { name: 'Dahua', links: ['Camera Analog Dahua', 'Camera IP Dahua', 'XVR Dahua', 'NVR Dahua', 'Videophone Dahua'] },
    ],
  },
  {
    name: 'Equipement Reseaux',
    sections: [
      { name: 'Armoire', links: ['Armoire Informatique Etanche', 'Armoire Informatique', "Accessoires d'Armoire"] },
      { name: 'Switch', links: ['Switch TP-Link', 'Switch PoE', 'Switch 8 port', 'Switch 16 port', 'Switch 24 port'] },
    ],
  },
  {
    name: 'Domotique',
    sections: [
      { name: 'Domotique', links: ['TAHOMA SOMFY', 'AKUVOX', 'Tuya', 'Sonoff', 'Shelly'] },
    ],
  },
  {
    name: 'Controle Dacces et Pointeuse',
    sections: [
      { name: "Controle D'acces", links: ["Controle d'acces hikvision", 'Serrure intelligente', "Controle D'acces ZKTeco", "Controle D'acces Dahua"] },
      { name: 'Pointeuse', links: ['Pointeuse hikvision', 'Pointeuse ZKTeco'] },
    ],
  },
  {
    name: 'Securite',
    sections: [
      { name: 'Detection intrusion', links: ['Cable alarm', 'Alarme Ajax', 'ALARME HIKVISION', 'Alarme Autonome', 'Alarme Dahua'] },
      { name: 'Detection incendie', links: ['Cable incendie', 'Incendie Nugelec', 'Incendie Adressable', 'Incendie conventionnelle', 'Alarme incendie'] },
    ],
  },
];

export const products = [
  {
    id: 1,
    brand: 'Dahua',
    category: 'Videosurveillance',
    subcategory: 'Camera IP Dahua',
    name: 'Dahua Camera IP Bullet 4MP PoE Full-color Network',
    price: 680,
    badge: '4MP PoE',
    image: dahuaBulletImage,
    stock: true,
  },
  {
    id: 3,
    brand: 'Dahua',
    category: 'Videosurveillance',
    subcategory: 'Camera IP Dahua',
    name: 'Dahua Camera IP Dome 2MP Wide View Night Vision',
    price: 520,
    badge: '2MP Dome',
    image: dahuaDomeImage,
    stock: true,
  },
  {
    id: 4,
    brand: 'Dahua',
    category: 'Videosurveillance',
    subcategory: 'Camera Analog Dahua',
    name: 'Dahua Camera Analogique 5MP Turret IR 40m',
    price: 450,
    badge: 'IR 40m',
    image: dahuacameraAnalogImage,
    stock: true,
  },
  {
    id: 5,
    brand: 'Hikvision',
    category: 'Videosurveillance',
    subcategory: 'Camera IP Hikvision',
    name: 'Hikvision Turbo HD PTZ SD2A500HB-GN-AW-PV-S2',
    price: 6000,
    badge: 'PTZ Wi-Fi',
    image: hikvisionTurboPtzImage,
    stock: true,
  },
  {
    id: 9,
    brand: 'Hikvision',
    category: 'Videosurveillance',
    subcategory: 'Camera IP Hikvision',
    name: 'Hikvision Camera IP Wi-Fi Ranger 2 IPC-A22EP-G',
    price: 384,
    badge: 'Best seller',
    image: hikvisionWifiRangerImage,
    stock: true,
  },
  {
    id: 21,
    brand: 'Hikvision',
    category: 'Videosurveillance',
    subcategory: 'Camera IP Hikvision',
    name: 'Camera IP Hikvision Bullet 4MP Lite Full-color',
    price: 624,
    badge: '4MP',
    image: hikvisionBulletImage,
    stock: true,
  },
  {
    id: 22,
    brand: 'Hikvision',
    category: 'Videosurveillance',
    subcategory: 'Camera Analog Hikvision',
    name: 'Camera Analogique 5MP IR 40m Bullet DS-2CE10KF0T-LFS',
    price: 420,
    badge: 'IR 40m',
    image: cameraAnalogImage,
    stock: true,
  },
  {
    id: 23,
    brand: 'Hikvision',
    category: 'Videosurveillance',
    subcategory: 'DVR Hikvision',
    name: 'DVR 2MP 4 channel DS-7204HGHI-M1',
    price: 546,
    badge: 'DVR',
    image: dvrImage,
    stock: false,
  },
  {
    id: 6,
    brand: 'Ruijie Reyee',
    category: 'Equipement Reseaux',
    name: 'Point acces exterieur RG-RAP6202(G) Wi-Fi 5 AC1300',
    price: 1625,
    badge: 'Outdoor',
    image: 'https://disismaroc.com/storage/products/16/381/disismaroc-point-dacces-exterieur-omnidirectionnel-rg-rap6202g-wi-fi-5-ac1300--1724167262-6802.png',
    stock: true,
  },
  {
    id: 7,
    brand: 'Ruijie Reyee',
    category: 'Equipement Reseaux',
    name: 'Routeur Mesh Wi-Fi 6 3200M dual band Gigabit',
    price: 1513.2,
    badge: 'Wi-Fi 6',
    image: 'https://disismaroc.com/storage/products/16/385/disismaroc-routeur-mesh-wi-fi-6-3200m-dual-band-gigabit-rg-ew3200gx-pro--1724168243-2597.png',
    stock: true,
  },
  {
    id: 8,
    brand: 'Sonoff',
    category: 'Domotique',
    subcategory: 'Sonoff',
    name: 'Sonoff 4CH Pro R3 module domotique',
    price: 395,
    badge: 'Smart home',
    image: sonoffModuleImage,
    stock: true,
  },
  {
    id: 10,
    brand: 'Dahua',
    category: 'Videosurveillance',
    subcategory: 'NVR Dahua',
    name: 'Dahua NVR 8 canaux PoE Resolution 4MP',
    price: 1380,
    badge: 'NVR 8CH PoE',
    image: dahuaNvrImage,
    stock: true,
  },
  {
    id: 24,
    brand: 'Hikvision',
    category: 'Videosurveillance',
    subcategory: 'NVR Hikvision',
    name: 'NVR Hikvision 8 canaux PoE pour camera IP',
    price: 1250,
    badge: 'NVR PoE',
    image: nvrImage,
    stock: true,
  },
  {
    id: 25,
    brand: 'Dahua',
    category: 'Videosurveillance',
    subcategory: 'XVR Dahua',
    name: 'Dahua XVR 4MP 8 canaux DVR/NVR Hybride',
    price: 890,
    badge: 'Hybride 8CH',
    image: dahuaXvrImage,
    stock: true,
  },
  {
    id: 26,
    brand: 'Hikvision',
    category: 'Videosurveillance',
    subcategory: 'Videophone Hikvision',
    name: 'Videophone IP ecran tactile 7 pouces avec interphone',
    price: 1850,
    badge: 'Videophone',
    image: videophoneImage,
    stock: true,
  },
  {
    id: 27,
    brand: 'Dahua',
    category: 'Videosurveillance',
    subcategory: 'Videophone Dahua',
    name: 'Dahua Videophone IP 7 pouces Ecran Tactile',
    price: 2150,
    badge: 'Videophone 7"',
    image: dahuaVideophoneImage,
    stock: true,
  },
  {
    id: 28,
    brand: 'ZKTeco',
    category: 'Controle Dacces et Pointeuse',
    subcategory: 'Pointeuse ZKTeco',
    name: 'Pointeuse ZKTeco biometrie empreinte et badge',
    price: 1450,
    badge: 'Pointage',
    image: pointeuseZktecoImage,
    stock: true,
  },
  {
    id: 29,
    brand: 'Hikvision',
    category: 'Controle Dacces et Pointeuse',
    subcategory: "Controle d'acces hikvision",
    name: "Terminal controle d'acces Hikvision badge RFID",
    price: 1180,
    badge: 'RFID',
    image: hikvisionAccessControlImage,
    stock: true,
  },
  {
    id: 30,
    brand: 'Dahua',
    category: 'Controle Dacces et Pointeuse',
    subcategory: "Controle D'acces Dahua",
    name: "Kit controle d'acces Dahua avec lecteur et alimentation",
    price: 980,
    badge: 'Kit acces',
    image: 'https://www.dynamic-computers.rs/images/products/big/134163.jpg',
    stock: true,
  },
  {
    id: 31,
    brand: 'Ajax',
    category: 'Securite',
    subcategory: 'Alarme Ajax',
    name: 'Kit alarme Ajax Hub avec detecteur mouvement',
    price: 2890,
    badge: 'Alarme',
    image: kitAlarmeAjaxImage,
    stock: true,
  },
  {
    id: 32,
    brand: 'Hikvision',
    category: 'Securite',
    subcategory: 'ALARME HIKVISION',
    name: 'Detecteur intrusion Hikvision sans fil PIR',
    price: 390,
    badge: 'Intrusion',
    image: detecteurIntrusionHikvisionImage,
    stock: true,
  },
  {
    id: 33,
    brand: 'Nugelec',
    category: 'Securite',
    subcategory: 'Incendie Nugelec',
    name: 'Detecteur incendie conventionnel avec sirene',
    price: 320,
    badge: 'Incendie',
    image: 'https://materiel-securite-incendie.fireless.fr/5740-large_default/detecteur-thermovelocimetrique-s3000-nug30247.jpg',
    stock: true,
  },
  {
    id: 34,
    brand: 'Alarm Cable',
    category: 'Securite',
    subcategory: 'Cable alarm',
    name: 'Cable alarme 6 conducteurs pour systeme intrusion',
    price: 180,
    badge: 'Cable alarm',
    image: cableAlarmeImage,
    stock: true,
  },
  {
    id: 35,
    brand: 'Dahua',
    category: 'Securite',
    subcategory: 'Alarme Dahua',
    name: 'Kit alarme Dahua sans fil avec sirene et detecteur',
    price: 1690,
    badge: 'Dahua',
    image: kitAlarmeDahuaImage,
    stock: true,
  },
  {
    id: 36,
    brand: 'Autonome',
    category: 'Securite',
    subcategory: 'Alarme Autonome',
    name: 'Alarme autonome avec sirene integree et detecteur',
    price: 590,
    badge: 'Autonome',
    image: alarmeAutonomeImage,
    stock: true,
  },
  {
    id: 37,
    brand: 'Fire Cable',
    category: 'Securite',
    subcategory: 'Cable incendie',
    name: 'Cable incendie CR1 rouge 2 conducteurs',
    price: 220,
    badge: 'Cable feu',
    image: cableIncendieImage,
    stock: true,
  },
  {
    id: 38,
    brand: 'Nugelec',
    category: 'Securite',
    subcategory: 'Incendie Adressable',
    name: 'Detecteur incendie adressable optique pour boucle SSI',
    price: 520,
    badge: 'Adressable',
    image: 'https://materiel-securite-incendie.fireless.fr/5740-large_default/detecteur-thermovelocimetrique-s3000-nug30247.jpg',
    stock: true,
  },
  {
    id: 39,
    brand: 'Nugelec',
    category: 'Securite',
    subcategory: 'Incendie conventionnelle',
    name: 'Detecteur incendie conventionnel optique avec base',
    price: 290,
    badge: 'Conventionnel',
    image: 'https://materiel-securite-incendie.fireless.fr/5740-large_default/detecteur-thermovelocimetrique-s3000-nug30247.jpg',
    stock: true,
  },
  {
    id: 40,
    brand: 'Securite Incendie',
    category: 'Securite',
    subcategory: 'Alarme incendie',
    name: 'Kit alarme incendie avec declencheur manuel et sirene',
    price: 1150,
    badge: 'Alarme feu',
    image: 'https://materiel-securite-incendie.fireless.fr/5740-large_default/detecteur-thermovelocimetrique-s3000-nug30247.jpg',
    stock: true,
  },
  {
    id: 45,
    brand: 'Linkbasic',
    category: 'Equipement Reseaux',
    subcategory: 'Armoire Informatique Etanche',
    name: 'Armoire informatique etanche murale 12U IP65',
    price: 2450,
    badge: 'IP65',
    image: Armoireinformatiqueetanche,
    stock: true,
  },
  {
    id: 46,
    brand: 'Digitus',
    category: 'Equipement Reseaux',
    subcategory: 'Armoire Informatique',
    name: 'Armoire informatique reseau 19 pouces 9U',
    price: 1550,
    badge: '19 pouces',
    image: Armoireinformatique,
    stock: true,
  },
  {
    id: 47,
    brand: 'Mortech',
    category: 'Equipement Reseaux',
    subcategory: "Accessoires d'Armoire",
    name: 'Plateau fixe et multiprise pour armoire reseau',
    price: 320,
    badge: 'Accessoire',
    image: Plateaufixe,
    stock: true,
  },
  {
    id: 48,
    brand: 'TP-Link',
    category: 'Equipement Reseaux',
    subcategory: 'Switch TP-Link',
    name: 'Switch TP-Link Gigabit 8 ports metal',
    price: 290,
    badge: 'TP-Link',
    image: switchTpLinkImage,
    stock: true,
  },
  {
    id: 49,
    brand: 'Ruijie Reyee',
    category: 'Equipement Reseaux',
    subcategory: 'Switch PoE',
    name: 'Switch PoE 8 ports pour cameras IP',
    price: 890,
    badge: 'PoE',
    image: switchPoeImage,
    stock: true,
  },
  {
    id: 50,
    brand: 'D-Link',
    category: 'Equipement Reseaux',
    subcategory: 'Switch 8 port',
    name: 'Switch reseau 8 ports Gigabit non manageable',
    price: 260,
    badge: '8 ports',
    image: switch8PortImage,
    stock: true,
  },
  {
    id: 51,
    brand: 'TP-Link',
    category: 'Equipement Reseaux',
    subcategory: 'Switch 16 port',
    name: 'Switch 16 ports Gigabit rackable',
    price: 760,
    badge: '16 ports',
    image: switch16PortImage,
    stock: true,
  },
  {
    id: 52,
    brand: 'Cisco',
    category: 'Equipement Reseaux',
    subcategory: 'Switch 24 port',
    name: 'Switch 24 ports Gigabit pour baie reseau',
    price: 1450,
    badge: '24 ports',
    image: switch24PortImage,
    stock: true,
  },
  {
    id: 53,
    brand: 'Somfy',
    category: 'Domotique',
    subcategory: 'TAHOMA SOMFY',
    name: 'Box domotique Somfy TaHoma Switch',
    price: 1890,
    badge: 'TaHoma',
    image: somfyTahomaImage,
    stock: true,
  },
  {
    id: 54,
    brand: 'Akuvox',
    category: 'Domotique',
    subcategory: 'AKUVOX',
    name: 'Moniteur interieur Akuvox pour maison connectee',
    price: 2450,
    badge: 'Akuvox',
    image: akuvoxMonitorImage,
    stock: true,
  },
  {
    id: 55,
    brand: 'Tuya',
    category: 'Domotique',
    subcategory: 'Tuya',
    name: 'Interrupteur intelligent Tuya Wi-Fi tactile',
    price: 180,
    badge: 'Tuya',
    image: tuyaSwitchImage,
    stock: true,
  },
  {
    id: 56,
    brand: 'Shelly',
    category: 'Domotique',
    subcategory: 'Shelly',
    name: 'Module relais Shelly Plus 1 Wi-Fi',
    price: 210,
    badge: 'Shelly',
    image: shellyRelayImage,
    stock: true,
  },
  {
    id: 62,
    brand: 'Mortech',
    category: 'Controle Dacces et Pointeuse',
    subcategory: 'Serrure intelligente',
    name: 'Serrure intelligente connectee avec clavier et badge',
    price: 1450,
    badge: 'Smart lock',
    image: smartLockImage,
    stock: true,
  },
  {
    id: 63,
    brand: 'ZKTeco',
    category: 'Controle Dacces et Pointeuse',
    subcategory: "Controle D'acces ZKTeco",
    name: "Controle d'acces ZKTeco autonome empreinte et RFID",
    price: 1280,
    badge: 'ZKTeco',
    image: 'https://zkteco.technology/wp-content/uploads/2022/01/c00444fc2e4cb4d4f513af79ca6e1fe3.png',
    stock: true,
  },
  {
    id: 64,
    brand: 'Hikvision',
    category: 'Controle Dacces et Pointeuse',
    subcategory: 'Pointeuse hikvision',
    name: 'Pointeuse Hikvision biometrie visage et badge',
    price: 1750,
    badge: 'Pointage',
    image: pointeuseHikvisionImage,
    stock: true,
  },
  {
    id: 65,
    brand: 'Hikvision',
    category: 'Securite',
    subcategory: 'Detection intrusion',
    name: 'Pack detection intrusion avec centrale, detecteur et sirene',
    price: 2190,
    badge: 'Intrusion',
    image: 'https://www.ctccommunications.com.au/cdn/shop/products/Hikvison-Wireless-PIR-Detector-DS-PDP15P-EG2-WB_1_ba917418-9201-478e-973f-3447445c2683_600x600.jpg?v=1752449306',
    stock: true,
  },
  {
    id: 66,
    brand: 'Nugelec',
    category: 'Securite',
    subcategory: 'Detection incendie',
    name: 'Pack detection incendie avec detecteur, declencheur et sirene',
    price: 1380,
    badge: 'Incendie',
    image: 'https://materiel-securite-incendie.fireless.fr/5740-large_default/detecteur-thermovelocimetrique-s3000-nug30247.jpg',
    stock: true,
  },
  {
    id: 67,
    brand: 'Kingston',
    category: 'Materiel Informatique',
    subcategory: 'RAM',
    name: 'RAM Kingston 16GB DDR4 3200MHz UDIMM',
    price: 450,
    badge: 'DDR4 16GB',
    image: ramMemoryImage,
    stock: true,
  },
  {
    id: 68,
    brand: 'SanDisk',
    category: 'Materiel Informatique',
    subcategory: 'SSDs',
    name: 'SanDisk SSD Plus 1TB SATA III',
    price: 1200,
    badge: 'SSD 1TB',
    image: sandiskSsdImage,
    stock: true,
  },
  {
    id: 69,
    brand: 'WD',
    category: 'Materiel Informatique',
    subcategory: 'Stockage portable',
    name: 'WD My Passport Disque dur externe portable 2TB',
    price: 1050,
    badge: 'Portable 2TB',
    image: portableDriveImage,
    stock: true,
  },
  {
    id: 70,
    brand: 'WD',
    category: 'Materiel Informatique',
    subcategory: 'HDD',
    name: 'WD Blue Disque dur interne 1TB 3.5 pouces',
    price: 680,
    badge: 'HDD 1TB',
    image: wdHddImage,
    stock: true,
  },
];

export const quickCategories = [
  ['Uniview Camera', 'Camera IP et NVR professionnels', Camera, 'Videosurveillance'],
  ['Hikvision Camera', 'Surveillance analogique et IP', ShieldCheck, 'Videosurveillance'],
  ['Domotique Sonoff', 'Modules connectes et capteurs', Home, 'Domotique'],
  ['Pointage ZKTeco', 'Pointeuses et controle acces', CircleUserRound, 'Controle Dacces et Pointeuse'],
  ['Ruijie sans fil', 'Wi-Fi entreprise et mesh', Network, 'Equipement Reseaux'],
];

export const dynamicHeroWords = ['Videosurveillance', 'Reseaux', 'Domotique', 'Controle acces', 'Informatique'];
